name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10'] 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools
        pip freeze >requirements.txt
        pip install -r requirements.txt
        pip install Django
        pip install django-allauth
        pip install django-crispy-forms
        pip install django-countries
        pip install stripe
        pip install Pillow
        pip install PyJWT
        pip install cryptography
    - name: Run Migration
      run: |
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Run Server
      run: |
          python3 manage.py runserver
