name: Django CI

on:
  issues:
    types: [opened]
  push:
    branches: [main]
  pull_request:
     branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools
          pip freeze >requirements.txt
          pip install -r requirements.txt
          pip install Django
          pip install django-allauth
          pip install django-crispy-forms
          pip install django-countries
          pip install stripe
          pip install Pillow
          pip install PyJWT
          pip install cryptography
          

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com" 
          echo "  login ${{ nivekrish43@gmail.com }}" 
          echo "  password ${{ secrets.HEROKU_API_KEY }}" 
          git remote add heroku https://git.heroku.com/arcane-retreat-52955.git${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku HEAD:main -f


